### ISSUE TITLE
checkpoint file names

### ISSUE THREAD

**Issue by antal-huck** [zubata88/mdgru#1]
experiments/\*/\*/cache/temp-0.ckpt.number -> temp-number.ckpt

final.ckpt-number -> final-number.ckpt or just final.ckpt but I think final-number.ckpt is still helpfull

**Comment by zubata88** [comment]
The postfix of the global step number is done in the tensorflow library, I hence don't want to override this functionality. I removed the ".ckpt" though, making the files in general look more normed, as they will be named "...final-number.index" or "...final-number.data" and the checkpointfile to be provided should now be "...final-number".
