### ISSUE TITLE
Dice-loss options are not passed on

### ISSUE THREAD

**Issue by BennoGesierich** [zubata88/mdgru#37]
Major issue:
Dice-loss options are not passed on to model class in RUN_mdgru.py

Minor issues:
Logging handler are added only in the runner.py script, not allowing logging of debug info in RUN_mdgru.py
Logging creates duplicate log messages.
Functions scipy.misc.imsave and scipy.misc.imread are deprecated in scipy 1.0.0. Suggesting to use imageio.imwrite and imageio.imread instead.

**Comment by zubata88** [comment]
fixed with #38
